name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 2

    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@v1

      - name: Prepare .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Build sln
        run: dotnet build

      - name: Evaluate
        uses: docker://ghcr.io/bmeviauac01/sflab-ahk:efrest-2022

      - name: Publish result
        uses: docker://ghcr.io/akosdudas/ahk-publish-results-pr:v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AHK_IMAGEEXT: ".png"
          AHK_APPTOKEN: "${{ secrets.AHK_APPTOKEN }}"
          AHK_APPSECRET: "${{ secrets.AHK_APPSECRET }}"
